/* automatically generated from display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (display_dialog_ui)
#endif
#ifdef __GNUC__
static const char display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkAdjustment\" id=\"adjustment1\"><property name=\"lo"
  "wer\">0.10</property><property name=\"upper\">10</property><property na"
  "me=\"step-increment\">0.10</property><property name=\"page-increment\">"
  "1</property></object><object class=\"GtkImage\" id=\"image3\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"icon-name\">window-close-symbolic</property></o"
  "bject><object class=\"GtkImage\" id=\"image4\"><property name=\"visible"
  "\">True</property><property name=\"can-focus\">False</property><propert"
  "y name=\"icon-name\">object-select-symbolic</property></object><object "
  "class=\"GtkListStore\" id=\"liststore1\"><columns><column type=\"gchara"
  "rray\"/><column type=\"gdouble\"/></columns><data><row><col id=\"0\">1x"
  "</col><col id=\"1\">1</col></row><row><col id=\"0\" translatable=\"yes\""
  ">1.25x</col><col id=\"1\">1.25</col></row><row><col id=\"0\" translatab"
  "le=\"yes\">1.5x</col><col id=\"1\">1.5</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">1.75x</col><col id=\"1\">1.75</col></row><row><col i"
  "d=\"0\" translatable=\"yes\">2x</col><col id=\"1\">2</col></row><row><c"
  "ol id=\"0\" translatable=\"yes\">Custom:</col><col id=\"1\">-1</col></r"
  "ow></data></object><object class=\"XfceTitledDialog\" id=\"display-dial"
  "og\"><property name=\"can-focus\">False</property><property name=\"titl"
  "e\" translatable=\"yes\">Display - Advanced Settings</property><propert"
  "y name=\"window-position\">center-on-parent</property><property name=\""
  "default-width\">400</property><property name=\"default-height\">400</pr"
  "operty><property name=\"icon-name\">org.xfce.settings.display</property"
  "><property name=\"type-hint\">dialog</property><child internal-child=\""
  "vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">False</property><pr"
  "operty name=\"orientation\">vertical</property><child internal-child=\""
  "action_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"layout-style\">end</property><child><"
  "object class=\"GtkButton\" id=\"button-close\"><property name=\"label\""
  " translatable=\"yes\">_Close</property><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">True</property><property name=\"image\">image3</prop"
  "erty><property name=\"use-underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">1</property></packing></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"pack-type\">end</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkBox\" id=\"plug-child\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"bor"
  "der-width\">6</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkBox"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"margin-top\">12</property><property"
  " name=\"margin-bottom\">12</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkBox\" id=\"display-settings\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"orientation\">vertical</property><property name="
  "\"spacing\">9</property><child><object class=\"GtkFrame\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"label-xalign\">0</property><property name=\"label-y"
  "align\">0</property><property name=\"shadow-type\">in</property><child>"
  "<object class=\"GtkAlignment\" id=\"randr-dnd\"><property name=\"width-"
  "request\">350</property><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><child><placeholder/></child></"
  "object></child><child type=\"label_item\"><placeholder/></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkGrid\"><property name=\"visible\">True"
  "</property><property name=\"can-focus\">False</property><property name="
  "\"row-spacing\">6</property><property name=\"column-spacing\">12</prope"
  "rty><child><object class=\"GtkSwitch\" id=\"mirror-displays\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">True</pro"
  "perty><property name=\"halign\">end</property><property name=\"valign\""
  ">center</property></object><packing><property name=\"left-attach\">0</p"
  "roperty><property name=\"top-attach\">0</property></packing></child><ch"
  "ild><object class=\"GtkLabel\" id=\"mirror-label\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">_Mirror displays</property><p"
  "roperty name=\"xalign\">0</property></object><packing><property name=\""
  "left-attach\">1</property><property name=\"top-attach\">0</property></p"
  "acking></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkG"
  "rid\" id=\"table1\"><property name=\"visible\">True</property><property"
  " name=\"can-focus\">False</property><property name=\"row-spacing\">3</p"
  "roperty><property name=\"column-spacing\">3</property><child><object cl"
  "ass=\"GtkBox\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"margin-bottom\">3</prop"
  "erty><property name=\"spacing\">12</property><child><object class=\"Gtk"
  "ComboBox\" id=\"randr-outputs\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">False</property><property name=\"hexpan"
  "d\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkSwitch\" id"
  "=\"output-on\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">True</property><property name=\"halign\">end</property><"
  "property name=\"valign\">center</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">0</property><property name=\"width\">4</property></packing></chil"
  "d><child><object class=\"GtkSwitch\" id=\"primary\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">True</property><pro"
  "perty name=\"halign\">end</property><property name=\"valign\">center</p"
  "roperty><property name=\"margin-bottom\">3</property></object><packing>"
  "<property name=\"left-attach\">2</property><property name=\"top-attach\""
  ">1</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel-primary\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"halign\">start</propert"
  "y><property name=\"margin-bottom\">3</property><property name=\"label\""
  " translatable=\"yes\">Primary Display:</property><property name=\"use-u"
  "nderline\">True</property></object><packing><property name=\"left-attac"
  "h\">1</property><property name=\"top-attach\">1</property></packing></c"
  "hild><child><object class=\"GtkComboBox\" id=\"randr-resolution\"><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">False"
  "</property><property name=\"margin-bottom\">3</property></object><packi"
  "ng><property name=\"left-attach\">2</property><property name=\"top-atta"
  "ch\">2</property></packing></child><child><object class=\"GtkLabel\" id"
  "=\"label-resolution\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"halign\">start</"
  "property><property name=\"margin-bottom\">3</property><property name=\""
  "label\" translatable=\"yes\">R_esolution:</property><property name=\"us"
  "e-underline\">True</property></object><packing><property name=\"left-at"
  "tach\">1</property><property name=\"top-attach\">2</property></packing>"
  "</child><child><object class=\"GtkComboBox\" id=\"randr-refresh-rate\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "False</property><property name=\"margin-bottom\">3</property></object><"
  "packing><property name=\"left-attach\">2</property><property name=\"top"
  "-attach\">5</property></packing></child><child><object class=\"GtkLabel"
  "\" id=\"label-refresh-rate\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"halign\">"
  "start</property><property name=\"margin-bottom\">3</property><property "
  "name=\"label\" translatable=\"yes\">Refresh _rate:</property><property "
  "name=\"use-underline\">True</property></object><packing><property name="
  "\"left-attach\">1</property><property name=\"top-attach\">5</property><"
  "/packing></child><child><object class=\"GtkComboBox\" id=\"randr-rotati"
  "on\"><property name=\"visible\">True</property><property name=\"can-foc"
  "us\">False</property><property name=\"margin-bottom\">3</property></obj"
  "ect><packing><property name=\"left-attach\">2</property><property name="
  "\"top-attach\">6</property></packing></child><child><object class=\"Gtk"
  "Label\" id=\"label-rotation\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">False</property><property name=\"halign\""
  ">start</property><property name=\"margin-bottom\">3</property><property"
  " name=\"label\" translatable=\"yes\">Ro_tation:</property><property nam"
  "e=\"use-underline\">True</property></object><packing><property name=\"l"
  "eft-attach\">1</property><property name=\"top-attach\">6</property></pa"
  "cking></child><child><object class=\"GtkComboBox\" id=\"randr-reflectio"
  "n\"><property name=\"can-focus\">False</property><property name=\"margi"
  "n-bottom\">3</property></object><packing><property name=\"left-attach\""
  ">2</property><property name=\"top-attach\">7</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label-reflection\"><property n"
  "ame=\"can-focus\">False</property><property name=\"halign\">start</prop"
  "erty><property name=\"margin-bottom\">3</property><property name=\"labe"
  "l\" translatable=\"yes\">Ref_lection:</property><property name=\"use-un"
  "derline\">True</property></object><packing><property name=\"left-attach"
  "\">1</property><property name=\"top-attach\">7</property></packing></ch"
  "ild><child><object class=\"GtkImage\" id=\"primary-indicator\"><propert"
  "y name=\"visible\">True</property><property name=\"can-focus\">False</p"
  "roperty><property name=\"valign\">center</property><property name=\"pix"
  "el-size\">16</property><property name=\"icon-name\">help-about-symbolic"
  "</property></object><packing><property name=\"left-attach\">0</property"
  "><property name=\"top-attach\">1</property></packing></child><child><ob"
  "ject class=\"GtkImage\" id=\"dummy-icon\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can-focus\">False</property><property nam"
  "e=\"pixel-size\">16</property></object><packing><property name=\"left-a"
  "ttach\">0</property><property name=\"top-attach\">2</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"hbox1\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "child><placeholder/></child><child><object class=\"GtkButton\" id=\"app"
  "ly\"><property name=\"label\" translatable=\"yes\">A_pply</property><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Tru"
  "e</property><property name=\"receives-default\">True</property><propert"
  "y name=\"margin-top\">6</property><property name=\"image\">image4</prop"
  "erty><property name=\"use-underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack-type\">end</property><property name=\"p"
  "osition\">1</property></packing></child></object><packing><property nam"
  "e=\"left-attach\">0</property><property name=\"top-attach\">8</property"
  "><property name=\"width\">3</property></packing></child><child><object "
  "class=\"GtkLabel\" id=\"label-scale\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">False</property><property name=\""
  "halign\">start</property><property name=\"label\" translatable=\"yes\">"
  "_Scale:</property><property name=\"use-underline\">True</property></obj"
  "ect><packing><property name=\"left-attach\">1</property><property name="
  "\"top-attach\">3</property></packing></child><child><object class=\"Gtk"
  "Revealer\" id=\"revealer-scale\"><property name=\"visible\">True</prope"
  "rty><property name=\"can-focus\">False</property><property name=\"revea"
  "l-child\">True</property><child><object class=\"GtkGrid\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"margin-top\">3</property><property name=\"margin-bo"
  "ttom\">3</property><property name=\"row-spacing\">3</property><child><o"
  "bject class=\"GtkLabel\" id=\"label-scale-x\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"halign\">end</property><property name=\"label\" translatable=\"y"
  "es\">X:</property><property name=\"xalign\">1</property></object><packi"
  "ng><property name=\"left-attach\">0</property><property name=\"top-atta"
  "ch\">0</property></packing></child><child><object class=\"GtkLabel\" id"
  "=\"label-scale-y\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"halign\">end</prope"
  "rty><property name=\"label\" translatable=\"yes\">Y:</property><propert"
  "y name=\"xalign\">1</property></object><packing><property name=\"left-a"
  "ttach\">0</property><property name=\"top-attach\">1</property></packing"
  "></child><child><object class=\"GtkSpinButton\" id=\"spin-scale-x\"><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Tru"
  "e</property><property name=\"halign\">end</property><property name=\"he"
  "xpand\">True</property><property name=\"text\" translatable=\"yes\">0.1"
  "</property><property name=\"adjustment\">adjustment1</property><propert"
  "y name=\"digits\">1</property><property name=\"value\">0.10</property><"
  "/object><packing><property name=\"left-attach\">1</property><property n"
  "ame=\"top-attach\">0</property></packing></child><child><object class=\""
  "GtkSpinButton\" id=\"spin-scale-y\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">True</property><property name=\"hal"
  "ign\">end</property><property name=\"hexpand\">True</property><property"
  " name=\"text\" translatable=\"yes\">0.1</property><property name=\"adju"
  "stment\">adjustment1</property><property name=\"digits\">1</property><p"
  "roperty name=\"value\">0.10</property></object><packing><property name="
  "\"left-attach\">1</property><property name=\"top-attach\">1</property><"
  "/packing></child><child><placeholder/></child><child><placeholder/></ch"
  "ild><child><placeholder/></child><child><placeholder/></child><child><p"
  "laceholder/></child></object></child></object><packing><property name=\""
  "left-attach\">2</property><property name=\"top-attach\">4</property></p"
  "acking></child><child><object class=\"GtkComboBox\" id=\"randr-scale\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "False</property><property name=\"model\">liststore1</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attribut"
  "es><attribute name=\"text\">0</attribute></attributes></child></object>"
  "<packing><property name=\"left-attach\">2</property><property name=\"to"
  "p-attach\">3</property></packing></child><child><placeholder/></child><"
  "child><placeholder/></child><child><placeholder/></child><child><placeh"
  "older/></child><child><placeholder/></child><child><placeholder/></chil"
  "d><child><placeholder/></child><child><placeholder/></child><child><pla"
  "ceholder/></child><child><placeholder/></child><child><placeholder/></c"
  "hild><child><placeholder/></child><child><placeholder/></child><child><"
  "placeholder/></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"pack-"
  "type\">end</property><property name=\"position\">1</property></packing>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkSeparator\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkGrid\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"border-width\">12</property><property name=\"row-spacin"
  "g\">6</property><property name=\"column-spacing\">12</property><child><"
  "object class=\"GtkLabel\" id=\"label-profile1\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"halign\">start</property><property name=\"margin-top\">12</pr"
  "operty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Connectin"
  "g Displays&lt;/b&gt;</property><property name=\"use-markup\">True</prop"
  "erty><property name=\"use-underline\">True</property></object><packing>"
  "<property name=\"left-attach\">0</property><property name=\"top-attach\""
  ">0</property><property name=\"width\">2</property></packing></child><ch"
  "ild><object class=\"GtkLabel\"><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Share settings across the same display product</p"
  "roperty><property name=\"xalign\">0</property></object><packing><proper"
  "ty name=\"left-attach\">1</property><property name=\"top-attach\">1</pr"
  "operty></packing></child><child><object class=\"GtkSwitch\" id=\"rlmode"
  "l-enable\"><property name=\"visible\">True</property><property name=\"c"
  "an-focus\">True</property><property name=\"halign\">end</property><prop"
  "erty name=\"valign\">center</property></object><packing><property name="
  "\"left-attach\">0</property><property name=\"top-attach\">1</property><"
  "/packing></child><child><object class=\"GtkLabel\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">Show popup windows to identif"
  "y displays</property><property name=\"xalign\">0</property></object><pa"
  "cking><property name=\"left-attach\">1</property><property name=\"top-a"
  "ttach\">2</property></packing></child><child><object class=\"GtkSwitch\""
  " id=\"identify-displays\"><property name=\"visible\">True</property><pr"
  "operty name=\"can-focus\">True</property><property name=\"halign\">end<"
  "/property><property name=\"valign\">center</property></object><packing>"
  "<property name=\"left-attach\">0</property><property name=\"top-attach\""
  ">2</property></packing></child></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">2</property></packing></child></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">2</property></packing></child></object></"
  "child><action-widgets><action-widget response=\"-7\">button-close</acti"
  "on-widget></action-widgets></object><object class=\"GtkListStore\" id=\""
  "liststore2\"><columns><column type=\"gchararray\"/><column type=\"guint"
  "\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Do nothing<"
  "/col><col id=\"1\">0</col></row><row><col id=\"0\" translatable=\"yes\""
  ">Show dialog</col><col id=\"1\">1</col></row></data></object></interfac"
  "e>"
};

static const unsigned display_dialog_ui_length = 19111u;

