/* automatically generated from display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (display_dialog_ui)
#endif
#ifdef __GNUC__
static const char display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkAdjustment\" id=\"adjustment1\"><property name=\"lo"
  "wer\">0.10</property><property name=\"upper\">10</property><property na"
  "me=\"step-increment\">0.10</property><property name=\"page-increment\">"
  "1</property></object><object class=\"GtkImage\" id=\"image3\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"icon-name\">window-close-symbolic</property></o"
  "bject><object class=\"GtkImage\" id=\"image4\"><property name=\"visible"
  "\">True</property><property name=\"can-focus\">False</property><propert"
  "y name=\"icon-name\">object-select-symbolic</property></object><object "
  "class=\"GtkListStore\" id=\"liststore1\"><columns><column type=\"gchara"
  "rray\"/><column type=\"gdouble\"/></columns><data><row><col id=\"0\">1x"
  "</col><col id=\"1\">1</col></row><row><col id=\"0\" translatable=\"yes\""
  ">1.25x</col><col id=\"1\">1.25</col></row><row><col id=\"0\" translatab"
  "le=\"yes\">1.5x</col><col id=\"1\">1.5</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">1.75x</col><col id=\"1\">1.75</col></row><row><col i"
  "d=\"0\" translatable=\"yes\">2x</col><col id=\"1\">2</col></row><row><c"
  "ol id=\"0\" translatable=\"yes\">Custom:</col><col id=\"1\">-1</col></r"
  "ow></data></object><object class=\"XfceTitledDialog\" id=\"display-dial"
  "og\"><property name=\"can-focus\">False</property><property name=\"titl"
  "e\" translatable=\"yes\">Display - Advanced Settings</property><propert"
  "y name=\"window-position\">center-on-parent</property><property name=\""
  "default-width\">400</property><property name=\"default-height\">400</pr"
  "operty><property name=\"icon-name\">org.xfce.settings.display</property"
  "><property name=\"type-hint\">dialog</property><child internal-child=\""
  "vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">False</property><pr"
  "operty name=\"orientation\">vertical</property><child internal-child=\""
  "action_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"layout-style\">end</property><child><"
  "object class=\"GtkButton\" id=\"button-close\"><property name=\"label\""
  " translatable=\"yes\">_Close</property><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">True</property><property name=\"image\">image3</prop"
  "erty><property name=\"use-underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">1</property></packing></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"pack-type\">end</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkBox\" id=\"plug-child\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"bor"
  "der-width\">6</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkBox"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"margin-top\">12</property><property"
  " name=\"margin-bottom\">12</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkBox\" id=\"display-settings\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"orientation\">vertical</property><property name="
  "\"spacing\">9</property><child><object class=\"GtkFrame\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"label-xalign\">0</property><property name=\"label-y"
  "align\">0</property><property name=\"shadow-type\">in</property><child>"
  "<object class=\"GtkAlignment\" id=\"randr-dnd\"><property name=\"width-"
  "request\">350</property><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><child><placeholder/></child></"
  "object></child><child type=\"label_item\"><placeholder/></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkCheckButton\" id=\"mirror-displays\"><"
  "property name=\"label\" translatable=\"yes\">_Mirror displays</property"
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">True</property><property name=\"receives-default\">False</property><pr"
  "operty name=\"use-underline\">True</property><property name=\"draw-indi"
  "cator\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkGrid\" id=\"table1\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">False</property><property name=\"row-spacin"
  "g\">3</property><property name=\"column-spacing\">3</property><child><o"
  "bject class=\"GtkBox\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"margin-bottom\""
  ">3</property><property name=\"spacing\">12</property><child><object cla"
  "ss=\"GtkComboBox\" id=\"randr-outputs\"><property name=\"visible\">True"
  "</property><property name=\"can-focus\">False</property><property name="
  "\"hexpand\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkSwit"
  "ch\" id=\"output-on\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">True</property><property name=\"halign\">end</pro"
  "perty><property name=\"valign\">center</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t><packing><property name=\"left-attach\">0</property><property name=\""
  "top-attach\">0</property><property name=\"width\">4</property></packing"
  "></child><child><object class=\"GtkSwitch\" id=\"primary\"><property na"
  "me=\"visible\">True</property><property name=\"can-focus\">True</proper"
  "ty><property name=\"halign\">end</property><property name=\"valign\">ce"
  "nter</property><property name=\"margin-bottom\">3</property></object><p"
  "acking><property name=\"left-attach\">2</property><property name=\"top-"
  "attach\">1</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"label-primary\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"halign\">start</"
  "property><property name=\"margin-bottom\">3</property><property name=\""
  "label\" translatable=\"yes\">Primary Display:</property><property name="
  "\"use-underline\">True</property></object><packing><property name=\"lef"
  "t-attach\">1</property><property name=\"top-attach\">1</property></pack"
  "ing></child><child><object class=\"GtkComboBox\" id=\"randr-resolution\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"margin-bottom\">3</property></object>"
  "<packing><property name=\"left-attach\">2</property><property name=\"to"
  "p-attach\">2</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label-resolution\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">False</property><property name=\"halign\">s"
  "tart</property><property name=\"margin-bottom\">3</property><property n"
  "ame=\"label\" translatable=\"yes\">R_esolution:</property><property nam"
  "e=\"use-underline\">True</property></object><packing><property name=\"l"
  "eft-attach\">1</property><property name=\"top-attach\">2</property></pa"
  "cking></child><child><object class=\"GtkComboBox\" id=\"randr-refresh-r"
  "ate\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">False</property><property name=\"margin-bottom\">3</property></ob"
  "ject><packing><property name=\"left-attach\">2</property><property name"
  "=\"top-attach\">5</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"label-refresh-rate\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"hal"
  "ign\">start</property><property name=\"margin-bottom\">3</property><pro"
  "perty name=\"label\" translatable=\"yes\">Refresh _rate:</property><pro"
  "perty name=\"use-underline\">True</property></object><packing><property"
  " name=\"left-attach\">1</property><property name=\"top-attach\">5</prop"
  "erty></packing></child><child><object class=\"GtkComboBox\" id=\"randr-"
  "rotation\"><property name=\"visible\">True</property><property name=\"c"
  "an-focus\">False</property><property name=\"margin-bottom\">3</property"
  "></object><packing><property name=\"left-attach\">2</property><property"
  " name=\"top-attach\">6</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"label-rotation\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"ha"
  "lign\">start</property><property name=\"margin-bottom\">3</property><pr"
  "operty name=\"label\" translatable=\"yes\">Ro_tation:</property><proper"
  "ty name=\"use-underline\">True</property></object><packing><property na"
  "me=\"left-attach\">1</property><property name=\"top-attach\">6</propert"
  "y></packing></child><child><object class=\"GtkComboBox\" id=\"randr-ref"
  "lection\"><property name=\"can-focus\">False</property><property name=\""
  "margin-bottom\">3</property></object><packing><property name=\"left-att"
  "ach\">2</property><property name=\"top-attach\">7</property></packing><"
  "/child><child><object class=\"GtkLabel\" id=\"label-reflection\"><prope"
  "rty name=\"can-focus\">False</property><property name=\"halign\">start<"
  "/property><property name=\"margin-bottom\">3</property><property name=\""
  "label\" translatable=\"yes\">Ref_lection:</property><property name=\"us"
  "e-underline\">True</property></object><packing><property name=\"left-at"
  "tach\">1</property><property name=\"top-attach\">7</property></packing>"
  "</child><child><object class=\"GtkImage\" id=\"primary-indicator\"><pro"
  "perty name=\"visible\">True</property><property name=\"can-focus\">Fals"
  "e</property><property name=\"valign\">center</property><property name=\""
  "pixel-size\">16</property><property name=\"icon-name\">help-about-symbo"
  "lic</property></object><packing><property name=\"left-attach\">0</prope"
  "rty><property name=\"top-attach\">1</property></packing></child><child>"
  "<object class=\"GtkImage\" id=\"dummy-icon\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"pixel-size\">16</property></object><packing><property name=\"lef"
  "t-attach\">0</property><property name=\"top-attach\">2</property></pack"
  "ing></child><child><object class=\"GtkBox\" id=\"hbox1\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">False</propert"
  "y><child><placeholder/></child><child><object class=\"GtkButton\" id=\""
  "apply\"><property name=\"label\" translatable=\"yes\">A_pply</property>"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"receives-default\">True</property><prop"
  "erty name=\"margin-top\">6</property><property name=\"image\">image4</p"
  "roperty><property name=\"use-underline\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"pack-type\">end</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"left-attach\">0</property><property name=\"top-attach\">8</prope"
  "rty><property name=\"width\">3</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label-scale\"><property name=\"visible\">Tru"
  "e</property><property name=\"can-focus\">False</property><property name"
  "=\"halign\">start</property><property name=\"label\" translatable=\"yes"
  "\">_Scale:</property><property name=\"use-underline\">True</property></"
  "object><packing><property name=\"left-attach\">1</property><property na"
  "me=\"top-attach\">3</property></packing></child><child><object class=\""
  "GtkRevealer\" id=\"revealer-scale\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"re"
  "veal-child\">True</property><child><object class=\"GtkGrid\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"margin-top\">3</property><property name=\"margin"
  "-bottom\">3</property><property name=\"row-spacing\">3</property><child"
  "><object class=\"GtkLabel\" id=\"label-scale-x\"><property name=\"visib"
  "le\">True</property><property name=\"can-focus\">False</property><prope"
  "rty name=\"halign\">end</property><property name=\"label\" translatable"
  "=\"yes\">X:</property><property name=\"xalign\">1</property></object><p"
  "acking><property name=\"left-attach\">0</property><property name=\"top-"
  "attach\">0</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"label-scale-y\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"halign\">end</pr"
  "operty><property name=\"label\" translatable=\"yes\">Y:</property><prop"
  "erty name=\"xalign\">1</property></object><packing><property name=\"lef"
  "t-attach\">0</property><property name=\"top-attach\">1</property></pack"
  "ing></child><child><object class=\"GtkSpinButton\" id=\"spin-scale-x\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"halign\">end</property><property name=\""
  "hexpand\">True</property><property name=\"text\" translatable=\"yes\">0"
  ".1</property><property name=\"adjustment\">adjustment1</property><prope"
  "rty name=\"digits\">1</property><property name=\"value\">0.10</property"
  "></object><packing><property name=\"left-attach\">1</property><property"
  " name=\"top-attach\">0</property></packing></child><child><object class"
  "=\"GtkSpinButton\" id=\"spin-scale-y\"><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "halign\">end</property><property name=\"hexpand\">True</property><prope"
  "rty name=\"text\" translatable=\"yes\">0.1</property><property name=\"a"
  "djustment\">adjustment1</property><property name=\"digits\">1</property"
  "><property name=\"value\">0.10</property></object><packing><property na"
  "me=\"left-attach\">1</property><property name=\"top-attach\">1</propert"
  "y></packing></child><child><placeholder/></child><child><placeholder/><"
  "/child><child><placeholder/></child><child><placeholder/></child><child"
  "><placeholder/></child></object></child></object><packing><property nam"
  "e=\"left-attach\">2</property><property name=\"top-attach\">4</property"
  "></packing></child><child><object class=\"GtkComboBox\" id=\"randr-scal"
  "e\"><property name=\"visible\">True</property><property name=\"can-focu"
  "s\">False</property><property name=\"model\">liststore1</property><chil"
  "d><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attr"
  "ibutes><attribute name=\"text\">0</attribute></attributes></child></obj"
  "ect><packing><property name=\"left-attach\">2</property><property name="
  "\"top-attach\">3</property></packing></child><child><placeholder/></chi"
  "ld><child><placeholder/></child><child><placeholder/></child><child><pl"
  "aceholder/></child><child><placeholder/></child><child><placeholder/></"
  "child><child><placeholder/></child><child><placeholder/></child><child>"
  "<placeholder/></child><child><placeholder/></child><child><placeholder/"
  "></child><child><placeholder/></child><child><placeholder/></child><chi"
  "ld><placeholder/></child></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "ack-type\">end</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkSeparator\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child><child><object class=\"GtkGrid\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"border-width\">12</property><property name=\"row-sp"
  "acing\">6</property><property name=\"column-spacing\">12</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label-profile1\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">False</property><pr"
  "operty name=\"halign\">start</property><property name=\"margin-top\">12"
  "</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Conne"
  "cting Displays&lt;/b&gt;</property><property name=\"use-markup\">True</"
  "property><property name=\"use-underline\">True</property></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">0</property><property name=\"width\">2</property></packing></chil"
  "d><child><object class=\"GtkLabel\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">Share settings across the same display produ"
  "ct</property><property name=\"xalign\">0</property></object><packing><p"
  "roperty name=\"left-attach\">1</property><property name=\"top-attach\">"
  "1</property></packing></child><child><object class=\"GtkSwitch\" id=\"r"
  "lmodel-enable\"><property name=\"visible\">True</property><property nam"
  "e=\"can-focus\">True</property><property name=\"halign\">end</property>"
  "<property name=\"valign\">center</property></object><packing><property "
  "name=\"left-attach\">0</property><property name=\"top-attach\">1</prope"
  "rty></packing></child><child><object class=\"GtkLabel\"><property name="
  "\"visible\">True</property><property name=\"can-focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">Show popup windows to id"
  "entify displays</property><property name=\"xalign\">0</property></objec"
  "t><packing><property name=\"left-attach\">1</property><property name=\""
  "top-attach\">2</property></packing></child><child><object class=\"GtkSw"
  "itch\" id=\"identify-displays\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">True</property><property name=\"halign\""
  ">end</property><property name=\"valign\">center</property></object><pac"
  "king><property name=\"left-attach\">0</property><property name=\"top-at"
  "tach\">2</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">2</property></packing></child></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">2</property></packing></child></obje"
  "ct></child><action-widgets><action-widget response=\"-7\">button-close<"
  "/action-widget></action-widgets></object><object class=\"GtkListStore\""
  " id=\"liststore2\"><columns><column type=\"gchararray\"/><column type=\""
  "guint\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Do not"
  "hing</col><col id=\"1\">0</col></row><row><col id=\"0\" translatable=\""
  "yes\">Show dialog</col><col id=\"1\">1</col></row></data></object></int"
  "erface>"
};

static const unsigned display_dialog_ui_length = 18577u;

