/* automatically generated from minimal-display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (minimal_display_dialog_ui)
#endif
#ifdef __GNUC__
static const char minimal_display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char minimal_display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkImage\" id=\"image5\"><proper"
  "ty name=\"visible\">True</property><property name=\"can-focus\">False</"
  "property><property name=\"icon-name\">window-close-symbolic</property><"
  "/object><object class=\"GtkWindow\" id=\"dialog\"><property name=\"can-"
  "focus\">False</property><property name=\"title\" translatable=\"yes\">D"
  "isplays - Basic Settings</property><property name=\"window-position\">c"
  "enter</property><property name=\"icon-name\">org.xfce.settings.display<"
  "/property><property name=\"type-hint\">dialog</property><child><object "
  "class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">False</property><property name=\"border-w"
  "idth\">6</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkGrid\" i"
  "d=\"buttons\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"row-spacing\">3</propert"
  "y><child><object class=\"GtkBox\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"hexp"
  "and\">True</property><property name=\"orientation\">vertical</property>"
  "<property name=\"spacing\">3</property><child><object class=\"GtkRadioB"
  "utton\" id=\"display1\"><property name=\"width-request\">128</property>"
  "<property name=\"height-request\">128</property><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">True</property><propert"
  "y name=\"receives-default\">False</property><property name=\"halign\">c"
  "enter</property><property name=\"active\">True</property><property name"
  "=\"draw-indicator\">False</property><child><object class=\"GtkImage\" i"
  "d=\"image1\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property></object></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkLabel\" id=\"label1\"><property name=\"width-request\">1"
  "28</property><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Only Display 1</property><property name=\"ellipsize\">middle</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"left-attach\">0</p"
  "roperty><property name=\"top-attach\">0</property></packing></child><ch"
  "ild><object class=\"GtkBox\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"margin-le"
  "ft\">24</property><property name=\"hexpand\">True</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">3</pr"
  "operty><child><object class=\"GtkRadioButton\" id=\"mirror\"><property "
  "name=\"width-request\">128</property><property name=\"height-request\">"
  "128</property><property name=\"visible\">True</property><property name="
  "\"can-focus\">True</property><property name=\"receives-default\">False<"
  "/property><property name=\"halign\">center</property><property name=\"a"
  "ctive\">True</property><property name=\"draw-indicator\">False</propert"
  "y><property name=\"group\">display1</property><child><object class=\"Gt"
  "kImage\" id=\"image2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property></object></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"label2\"><property name=\"width-"
  "request\">128</property><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><property name=\"tooltip-text\""
  " translatable=\"yes\">Mirror Displays</property><property name=\"label\""
  " translatable=\"yes\">Mirror Displays</property><property name=\"ellips"
  "ize\">middle</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"left-attach\">1</property><property name=\"top-attach\">0</property><"
  "/packing></child><child><object class=\"GtkBox\"><property name=\"visib"
  "le\">True</property><property name=\"can-focus\">False</property><prope"
  "rty name=\"margin-left\">24</property><property name=\"hexpand\">True</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">3</property><child><object class=\"GtkRadioButton\" id=\""
  "extend_right\"><property name=\"width-request\">128</property><property"
  " name=\"height-request\">128</property><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">False</property><property name=\"halign\">center</pr"
  "operty><property name=\"active\">True</property><property name=\"draw-i"
  "ndicator\">False</property><property name=\"group\">display1</property>"
  "<child><object class=\"GtkImage\" id=\"image3\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label3\""
  "><property name=\"width-request\">128</property><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"tooltip-text\" translatable=\"yes\">Extend to the right</prop"
  "erty><property name=\"label\" translatable=\"yes\">Extend to the right<"
  "/property><property name=\"ellipsize\">middle</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing></child>"
  "</object><packing><property name=\"left-attach\">2</property><property "
  "name=\"top-attach\">0</property></packing></child><child><object class="
  "\"GtkBox\"><property name=\"visible\">True</property><property name=\"c"
  "an-focus\">False</property><property name=\"margin-left\">24</property>"
  "<property name=\"hexpand\">True</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">3</property><child><obje"
  "ct class=\"GtkRadioButton\" id=\"display2\"><property name=\"width-requ"
  "est\">128</property><property name=\"height-request\">128</property><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Tru"
  "e</property><property name=\"receives-default\">False</property><proper"
  "ty name=\"halign\">center</property><property name=\"active\">True</pro"
  "perty><property name=\"draw-indicator\">False</property><property name="
  "\"group\">display1</property><child><object class=\"GtkImage\" id=\"ima"
  "ge4\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">False</property></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"label4\"><property name=\"width-request\">128</pr"
  "operty><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">On"
  "ly Display 2</property><property name=\"ellipsize\">middle</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"left-attach\">3</proper"
  "ty><property name=\"top-attach\">0</property></packing></child></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkButtonBox\" id=\"hbuttonbox1\"><propert"
  "y name=\"visible\">True</property><property name=\"can-focus\">False</p"
  "roperty><child><object class=\"GtkButton\" id=\"advanced_button\"><prop"
  "erty name=\"label\" translatable=\"yes\">_Advanced</property><property "
  "name=\"visible\">True</property><property name=\"can-focus\">True</prop"
  "erty><property name=\"receives-default\">True</property><property name="
  "\"use-underline\">True</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkRadioButton\" id=\"fake_button\"><property name=\"label\" translatab"
  "le=\"yes\">radiobutton</property><property name=\"can-focus\">True</pro"
  "perty><property name=\"receives-default\">False</property><property nam"
  "e=\"active\">True</property><property name=\"draw-indicator\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">3</prope"
  "rty></packing></child><child><object class=\"GtkButton\" id=\"cancel_bu"
  "tton\"><property name=\"label\" translatable=\"yes\">_Close</property><"
  "property name=\"visible\">True</property><property name=\"can-focus\">T"
  "rue</property><property name=\"receives-default\">True</property><prope"
  "rty name=\"image\">image5</property><property name=\"use-underline\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">4"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"pack-type\">end</property><property name=\"position\">1</property></p"
  "acking></child></object></child></object></interface>"
};

static const unsigned minimal_display_dialog_ui_length = 9261u;

